import Enterprise from "../../entities/Enterprise";

export const lightTheme = (name: string, insertedEnterprise: Enterprise) => ({
  name: `${name}`,
  primary_color: "#1976D2",
  secondary_color: "#42A5F5",
  tertiary_color: "#90CAF9",
  quaternary_color: "#E3F2FD",
  background_color: "#F5F5F5",
  surface_color: "#FFFFFF",
  text_primary_color: "#212121",
  text_secondary_color: "#757575",
  border_color: "#E0E0E0",
  error_color: "#D32F2F",
  success_color: "#388E3C",
  btn_primary_bg: "#1976D2",
  btn_primary_text: "#FFFFFF",
  btn_secondary_bg: "#EEEEEE",
  btn_secondary_text: "#212121",
  btn_tertiary_bg: "#FFFFFF",
  btn_tertiary_text: "#212121",
  btn_quaternary_bg: "#F5F5F5",
  btn_quaternary_text: "#212121",
  heading_color: "#212121",
  subheading_color: "#424242",
  text_default: "#212121",
  text_muted: "#9E9E9E",
  link_color: "#1976D2",
  link_hover_color: "#1565C0",
  input_bg: "#FFFFFF",
  input_text: "#212121",
  input_border: "#E0E0E0",
  input_placeholder: "#9E9E9E",
  input_focus_border: "#1976D2",
  app_background: "#FAFAFA",
  card_background: "#FFFFFF",
  card_border: "#E0E0E0",
  card_shadow: "0px 1px 3px rgba(0,0,0,0.1)",
  drawer_bg: "#FFFFFF",
  drawer_text: "#212121",
  drawer_border: "#E0E0E0",
  drawer_hover_bg: "#F5F5F5",
  drawer_active_bg: "#E3F2FD",
  logo: "",
  favicon: "",
  enterprise_id: insertedEnterprise.id,
  theme: "light",
});

// Criar tema dark
export const darkTheme = (name: string, insertedEnterprise: Enterprise) => ({
  name: `${name}`,
  primary_color: "#90CAF9",
  secondary_color: "#64B5F6",
  tertiary_color: "#42A5F5",
  quaternary_color: "#1976D2",
  background_color: "#121212",
  surface_color: "#1E1E1E",
  text_primary_color: "#FFFFFF",
  text_secondary_color: "#B0BEC5",
  border_color: "#424242",
  error_color: "#EF5350",
  success_color: "#66BB6A",
  btn_primary_bg: "#42A5F5",
  btn_primary_text: "#FFFFFF",
  btn_secondary_bg: "#2C2C2C",
  btn_secondary_text: "#FFFFFF",
  btn_tertiary_bg: "#1E1E1E",
  btn_tertiary_text: "#E0E0E0",
  btn_quaternary_bg: "#121212",
  btn_quaternary_text: "#FFFFFF",
  heading_color: "#FFFFFF",
  subheading_color: "#E0E0E0",
  text_default: "#E0E0E0",
  text_muted: "#9E9E9E",
  link_color: "#90CAF9",
  link_hover_color: "#E3F2FD",
  input_bg: "#1E1E1E",
  input_text: "#FFFFFF",
  input_border: "#424242",
  input_placeholder: "#B0BEC5",
  input_focus_border: "#64B5F6",
  app_background: "#121212",
  card_background: "#1E1E1E",
  card_border: "#2C2C2C",
  card_shadow: "0px 1px 3px rgba(255,255,255,0.05)",
  drawer_bg: "#1E1E1E",
  drawer_text: "#FFFFFF",
  drawer_border: "#2C2C2C",
  drawer_hover_bg: "#2A2A2A",
  drawer_active_bg: "#1976D2",
  logo: "",
  favicon: "",
  enterprise_id: insertedEnterprise.id,
  theme: "dark",
});

export const defaultServices = (insertedEnterprise: Enterprise) => [
  {
    title: "Barba",
    description: "Barba completa",
    price: 10,
    duration: 60,
    enterprise_id: insertedEnterprise.id,
  },
  {
    title: "Corte de cabelo",
    description: "Corte de cabelo",
    price: 10,
    duration: 30,
    enterprise_id: insertedEnterprise.id,
  },
];
